[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zeroai_program = "FDkZRiRJapBGTmcr9u8dQtHEk9VbDsb4E9dY4NYPLkJ3"

[programs.devnet]
zeroai_program = "FDkZRiRJapBGTmcr9u8dQtHEk9VbDsb4E9dY4NYPLkJ3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]] # PYTH devnet BTC Feed
address = "HovQMDrbAgAYPCmHVSrezcSmkMtXSSUsLDFANExrZh2J"

[[test.validator.clone]] # PYTH devnet ETH Feed
address = "EdVCmQ9FSPcVe5YySXDPCRmc8aDQLKJ9xvYBMZPie1Vw"

[[test.validator.clone]] # PYTH devnet SOL Feed
address = "J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix"

[[test.validator.clone]] # PYTH devnet BNB Feed
address = "GwzBgrXb4PG59zjce24SF2b9JXbLEjJJTBkmytuEZj1b"

[[test.validator.clone]] # PYTH devnet DOGE Feed
address = "4L6YhY8VvUgmqG5MvJkUJATtzB2rFqdrJwQCmFLv4Jzy"

[[test.validator.clone]] # PYTH devnet JUP Feed
address = "Gh9hscza9YaCzr84tNV1NZQfpqoL3csYnWDygDkQmBU2"